### ISSUE TITLE
Can I use this on StackBlitz?

### ISSUE THREAD

**Issue by cyrfer** [stackblitz/eslint-plugin#19]
When I try to add this as a dependency to my React Typescript project in stackblitz, I get this error:

<div class="msg-body">Unable to find package <span class="depName">@blitz/eslint-plugin</span> in the NPM registry.<br>Please try installing a different package name.</div>

**Comment by d3lm** [comment]
This package is not published to npm as a public package at this point, that's why you can't install it. Is there a particular reason why you want to install this to your project?

I am going to close this issue for now.

**Comment by cyrfer** [comment]
I want to learn how to customize eslint in a Monorepo using stackblitz
